// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr78CBVdW9ftMYJ_rfuUuCOrmHOCRljzg',
    appId: '1:365558610801:web:71c5e292c12460ffc8d4d0',
    messagingSenderId: '365558610801',
    projectId: 'expenseapp-e08d5',
    authDomain: 'expenseapp-e08d5.firebaseapp.com',
    storageBucket: 'expenseapp-e08d5.appspot.com',
    measurementId: 'G-ZBQK81WLVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5F5LRphQS5KkIU_MTz2WibCpAECfEOoc',
    appId: '1:365558610801:android:7e9ba026e318aa02c8d4d0',
    messagingSenderId: '365558610801',
    projectId: 'expenseapp-e08d5',
    storageBucket: 'expenseapp-e08d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAwAjsU0xUGt7C9aoK7zlbLMZHau3IkrY',
    appId: '1:365558610801:ios:8041967b798080f4c8d4d0',
    messagingSenderId: '365558610801',
    projectId: 'expenseapp-e08d5',
    storageBucket: 'expenseapp-e08d5.appspot.com',
    iosBundleId: 'com.example.expenseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAwAjsU0xUGt7C9aoK7zlbLMZHau3IkrY',
    appId: '1:365558610801:ios:b4ffd7d6eeb7a5dcc8d4d0',
    messagingSenderId: '365558610801',
    projectId: 'expenseapp-e08d5',
    storageBucket: 'expenseapp-e08d5.appspot.com',
    iosBundleId: 'com.example.expenseapp.RunnerTests',
  );
}
